test

diff --git a/.github/workflows/jenkins_tests_execution.yml b/.github/workflows/jenkins_tests_execution.yml
--- a/.github/workflows/jenkins_tests_execution.yml
+++ b/.github/workflows/jenkins_tests_execution.yml
@@ -6,7 +6,7 @@ on:
   #push:
   #  branches: [ main ]
   pull_request:
-    branches: [ main ]
+    branches: [ gha_jenkins_script ]
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
@@ -17,7 +17,7 @@ jobs:
     build:
 
       if: >-
-        github.event.pull_request.user.login == 'user1' ||
+        github.event.pull_request.user.login == 'lukaszgda' ||
         github.event.pull_request.user.login == 'user2'
 
       # The type of runner that the job will run on
@@ -29,35 +29,40 @@ jobs:
       steps:
         - name: Clone the git repo
           uses: actions/checkout@v2
-
-        # Executing jenkins job
+        
+        Executing jenkins job
         - name: Executing jenkins job
           run: |
-            curlOutput=`curl -XPOST --insecure --silent --show-error -u $jenkins_user:$jenkins_token $job_address/buildWithParameters?token=$job_token`
-            if [[ "$curlOutput" == *"Error"* ]]; then
-              echo $curlOutput
-              exit 1
-            fi
+            echo ${{ github.event.pull_request }}
 
-            sleep 10
+        # Executing jenkins job
+        # - name: Executing jenkins job
+        #   run: |
+        #     curlOutput=`curl -XPOST --insecure --silent --show-error -u $jenkins_user:$jenkins_token $job_address/buildWithParameters?token=$job_token`
+        #     if [[ "$curlOutput" == *"Error"* ]]; then
+        #       echo $curlOutput
+        #       exit 1
+        #     fi
 
-            curlJsonBuildOutput=`curl --insecure -u $jenkins_user:$jenkins_token $job_address/lastBuild/api/json | jq -r '.building'`
+        #     sleep 10
 
-            while [[ "$curlJsonBuildOutput" == "true" ]]
-             do
-              sleep 10
-              curlJsonBuildOutput=`curl --insecure -u $jenkins_user:$jenkins_token $job_address/lastBuild/api/json | jq -r '.building'`
-            done
+        #     curlJsonBuildOutput=`curl --insecure -u $jenkins_user:$jenkins_token $job_address/lastBuild/api/json | jq -r '.building'`
 
-        - name: Show Jenkins job log
-          run: |
-            curl --insecure -u $jenkins_user:$jenkins_token $job_address/lastBuild/consoleText
+        #     while [[ "$curlJsonBuildOutput" == "true" ]]
+        #      do
+        #       sleep 10
+        #       curlJsonBuildOutput=`curl --insecure -u $jenkins_user:$jenkins_token $job_address/lastBuild/api/json | jq -r '.building'`
+        #     done
 
-        - name: Validating job's status
-          run: |
-            curlJsonResultOutput=`curl --insecure -u $jenkins_user:$jenkins_token $job_address/lastBuild/api/json | jq -r '.result'`
+        # - name: Show Jenkins job log
+        #   run: |
+        #     curl --insecure -u $jenkins_user:$jenkins_token $job_address/lastBuild/consoleText
 
-            if [[ "$curlJsonResultOutput" == "FAILURE" ]]; then
-              echo "Jenkins job failed!"
-              exit 1
-            fi
+        # - name: Validating job's status
+        #   run: |
+        #     curlJsonResultOutput=`curl --insecure -u $jenkins_user:$jenkins_token $job_address/lastBuild/api/json | jq -r '.result'`
+
+        #     if [[ "$curlJsonResultOutput" == "FAILURE" ]]; then
+        #       echo "Jenkins job failed!"
+        #       exit 1
+        #     fi
